### ISSUE TITLE
Please consider porting to v0.19 

### ISSUE THREAD

**Issue by luzpaz** [alunmorgan/EM_CAD_frontend#2]
Since v0.19 is pending release...it would be advantageous to be ready in time for it.

**Comment by alunmorgan** [comment]
Thanks for the heads up. I will have a look at v0.19

**Comment by luzpaz** [comment]
@alunmorgan thanks! It would be a good move since there is a target to release it by the end of this year.

**Comment by alunmorgan** [comment]
All checked and working with 0.19
